/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Hp' at '1/11/20 1:28 PM' with Gradle 3.0
 *
 * @author Hp, @date 1/11/20 1:28 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
